project/app/urls.py
from django.urls import path
from . import views

app_name = 'app'
urlpatterns = [
    path('', views.MesIndexView.as_view(), name='index'),
    path('add/', views.MesAddView.as_view(), name='add'),
    path('change/<int:pk>', views.MesChangeView.as_view(), name='change'),
    path('delete/<int:pk>', views.MesDeleteView.as_view(), name='delete'),
    path('create_user/', views.UserCreateView.as_view(), name='create_user'),
]

project/project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls', namespace='app')),
]

project/app/models.py
from django.db import models


class Message(models.Model):
    text = models.CharField("テキスト", max_length=255)

    def __str__(self):
        return self.text

project/app/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm


KIND = (
    ("user", "権限を追加（投稿のみ）"),
    ("group", "グループの権限を追加（編集と削除）"),
)


class UserCreateForm(UserCreationForm):
    kind = forms.ChoiceField(label="権限の設定", choices=KIND)

project/app/views.py
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.contrib.auth.models import Permission, Group
from django.urls import reverse_lazy
from django.http import HttpResponseRedirect
from django.views import generic
from .models import Message
from .forms import UserCreateForm


class MesIndexView(generic.ListView):
    model = Message


class MesAddView(PermissionRequiredMixin, generic.CreateView):
    model = Message
    fields = "__all__"
    success_url = reverse_lazy("app:index")
    permission_required = ("app.add_message",)
    raise_exception = True


class MesChangeView(PermissionRequiredMixin, generic.UpdateView):
    model = Message
    fields = "__all__"
    success_url = reverse_lazy("app:index")
    permission_required = ("app.change_message",)
    raise_exception = True


class MesDeleteView(PermissionRequiredMixin, generic.DeleteView):
    model = Message
    fields = "__all__"
    success_url = reverse_lazy("app:index")
    permission_required = ("app.delete_message",)
    raise_exception = True


class UserCreateView(PermissionRequiredMixin, generic.CreateView):
    form_class = UserCreateForm
    template_name = "app/user_form.html"
    success_url = reverse_lazy("app:index")
    permission_required = ("auth.add_user")
    raise_exception = True

    def form_valid(self, form):
        user = form.save(commit=False)
        user.is_staff = True
        user.save()
        kind = form.cleaned_data["kind"]
        if kind == "user":
            permission = Permission.objects.get(codename="add_message")
            user.user_permissions.add(permission)
        elif kind == "group":
            group = Group.objects.get(name='can-edit-and-delete-group')
            user.groups.add(group)
        else:
            pass  # ここには「基本的」に来ない。raise Http404 とかしといても良いかもしれない

        return HttpResponseRedirect(self.success_url)

project/app/templates/app/base.html
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="utf-8">
  </head>
  <body>
    {% block content %} {% endblock %}
  </body>
</html>

project/app/templates/app/message_confirm_delete.html
{% extends "app/base.html" %}
{% block content %}
  <p>{{ message.text }}</p>
　　<form action="" method="POST">
　　　　{{ form.as_p }}
    {% csrf_token %}
    <input type="submit" value="削除する">
  </form>
{% endblock %}

project/app/templates/app/message_form.html
{% extends "app/base.html" %}
{% block content %}
　　<form action="" method="POST">
　　　　{{ form.as_p }}
    {% csrf_token %}
    <input type="submit" value="送信">
  </form>
{% endblock %}

project/app/templates/app/message_list.html
{% extends "app/base.html" %}
{% block content %}

  {% if perms.app.add_message %}
    <p><a href="{% url 'app:add' %}">新規追加</a></p>
  {% endif %}

  {% if perms.auth.add_user %}
    <p><a href="{% url 'app:create_user' %}">ユーザの追加</a></p>
  {% endif %}

  <hr>
  {% for message in message_list %}
    <p>
    　 {{ message.text }}

      {% if perms.app.change_message %}
        <a href="{% url 'app:change' message.pk %}">変更する</a>
      {% endif %}
    　　
      {% if perms.app.delete_message %}
        <a href="{% url 'app:delete' message.pk %}">削除する</a>
      {% endif %}

   　</p>
  {% endfor %}
{% endblock %}

project/app/templates/app/user_form.html
{% extends "app/base.html" %}
{% block content %}
　　<form action="" method="POST">
　　　　{{ form.as_p }}
    {% csrf_token %}
    <input type="submit" value="送信">
  </form>
{% endblock %}